---
- name: apache-vhosts - create factice certificate
  command: "openssl req -new -nodes -x509 -subj '/C=FR/L=Paris/O=FR/CN={{ domain}}' -days 3650 -keyout /etc/ssl/private/{{ domain }}.key -out /etc/ssl/certs/{{ domain }}.crt"

- name: apache-vhosts - remove default vhost
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: apache-vhosts - create vhost
  template:
    src: "{{ application }}-vhost.j2"
    dest: "/etc/apache2/sites-available/{{ domain }}.conf"

- name: apache-vhosts - active vhost
  file:
    src: "/etc/apache2/sites-available/{{ domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ domain }}.conf"
    state: link

- name: apache-vhosts - create repository main dir
  file:
    dest: "/var/www/{{ name }}"
    owner: www-data
    group: www-data
    state: directory
  when: create_root_dir

- name: apache-vhosts - enable modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - ssl
    - rewrite

- name: apache-vhosts - be sure apache is started
  service:
    name: apache2
    state: started

- name: apache-vhosts - reload apache
  service:
    name: apache2
    state: reloaded
