---
- name: apache-vhosts - create factice certificate
  # command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt
  command: openssl req -new -nodes -x509 -subj "/C=FR/L=Paris/O=FR/CN=madef.fr" -days 3650 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt

- name: apache-vhosts - remove default vhost
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: apache-vhosts - create prestashop vhost
  template:
    src: prestashop-vhost.j2
    dest: "/etc/apache2/sites-available/{{ item.domain }}.conf"
  with_items: "{{ apache_vhosts.prestashop }}"

- name: apache-vhosts - create repository vhost
  template:
    src: repo-vhost.j2
    dest: "/etc/apache2/sites-available/{{ item.domain }}.conf"
  with_items: "{{ apache_vhosts.repo }}"

- name: apache-vhosts - active prestashop vhost
  file:
    src: "/etc/apache2/sites-available/{{ item.domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item.domain }}.conf"
    state: link
  with_items: "{{ apache_vhosts.prestashop }}"

- name: apache-vhosts - active repository vhost
  file:
    src: "/etc/apache2/sites-available/{{ item.domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item.domain }}.conf"
    state: link
  with_items: "{{ apache_vhosts.repo }}"

- name: apache-vhosts - create repository main dir
  file:
    dest: "/var/www/{{ item.name }}"
    owner: www-data
    group: www-data
    state: directory
  with_items: "{{ apache_vhosts.repo }}"

- name: apache-vhosts - enable modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - ssl
    - rewrite

- name: apache-vhosts - be sure apache is started
  service:
    name: apache2
    state: started

- name: apache-vhosts - reload apache
  service:
    name: apache2
    state: reloaded
