---
- name: apache-vhosts - create vhost
  template:
    src: prestashop-vhost.j2
    dest: "/etc/apache2/sites-available/{{ item.domain }}.conf"
  with_items: "{{ apache_vhosts.prestashop }}"

- name: apache-vhosts - active vhost
  file:
    src: "/etc/apache2/sites-available/{{ item.domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item.domain }}.conf"
    state: link
  with_items: "{{ apache_vhosts.prestashop }}"

- name: apache-vhosts - enable modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - ssl
    - rewrite

- name: apache-vhosts - be sure apache is started
  service:
    name: apache2
    state: started

- name: apache-vhosts - reload apache
  service:
    name: apache2
    state: reloaded
