---
ansible_user: root
ansible_host: etno.madef.fr

apache_vhosts:
  prestashop:
    - name: advancedimporter
      domain: advancedimporter.prestashop.demo.madef.fr
      is_demo: yes
      version: 1.6.1.13
      modules:
        - advancedimporter
    - name: advancedrelatedproduct
      domain: advancedrelatedproduct.prestashop.demo.madef.fr
      version: 1.6.1.13
      is_demo: yes
      modules:
        - advancedrelatedproduct
    - name: responsivemenu
      domain: responsivemenu.prestashop.demo.madef.fr
      version: 1.6.1.13
      is_demo: yes
      modules:
        - responsivemenu
    - name: prestapicto
      domain: prestapicto.prestashop.demo.madef.fr
      version: 1.6.1.13
      is_demo: yes
      modules:
        - prestapicto
    - name: prestapress
      domain: prestapress.prestashop.demo.madef.fr
      version: 1.6.1.13
      is_demo: yes
      modules:
        - prestapress
    - name: blog
      domain: blog.deflotte.fr
      version: 1.6.1.13
      is_demo: no
      modules:
        - prestapress
