---
ansible_user: root
ansible_host: 91.121.68.131 #stereo.madef.fr

databases:
  - name: ps_advancedimporter
    user: ps_advancedimporter
    password: test00test # Replace and crypt
    host: 37.187.55.118
  - name: ps_advancedrelatedproduct
    user: ps_advancedrelatedproduct
    password: test00test # Replace and crypt
    host: 37.187.55.118
  - name: ps_responsivemenu
    user: ps_responsivemenu
    password: test00test # Replace and crypt
    host: 37.187.55.118
  - name: ps_prestapicto
    user: ps_prestapicto
    password: test00test # Replace and crypt
    host: 37.187.55.118
  - name: ps_prestapress
    user: ps_prestapress
    password: test00test # Replace and crypt
    host: 37.187.55.118
  - name: ps_blog
    user: ps_blog
    password: test00test # Replace and crypt
    host: 37.187.55.118
