---
- name: prestashop - create demo profile
  command: "php /var/www/{{ name }}/admin-tools/console.php profile:create -n demo2"
  when: is_demo

- name: prestashop - create demo user
  command: "php /var/www/{{ name }}/admin-tools/console.php employee:create -l demo -f demo -p demodemo -e demo2@demo.com -P demo2 -L en"
  when: is_demo

- name: prestashop - create demo user
  command: "php /var/www/{{ name }}/admin-tools/console.php employee:create -l demo -f demo -p demodemo -e demo2@demo.fr -P demo2 -L fr"
  when: is_demo

- name: prestashop - set demo right (display, add, remove, edit)
  command: "php /var/www/{{ name }}/admin-tools/console.php profile:access -p demo2 -t {{ item }} -d -a -e -r"
  with_items:
    - SELL
    - IMPROVE
    - CONFIGURE
    - AdminWelcome
    - AdminDashboard
    - DEFAULT
    - AdminCatalog
    - AdminProducts
    - AdminCategories
    - AdminFeatures
    - AdminManufacturers
    - AdminSuppliers
    - AdminTags
    - AdminAttachments
    - AdminModulesPositions
  when: is_demo

- name: prestashop - set demo right (display, add, remove, edit)
  command: "php /var/www/{{ name }}/admin-tools/console.php profile:access -p demo2 -t {{ item }} -d -a -e -r"
  with_items:
    - AdminAdvancedImporter%
  when: is_demo
  ignore_errors: yes

- name: prestashop - set demo right (display)
  command: "php /var/www/{{ name }}/admin-tools/console.php profile:access -p demo2 -t {{ item }} -d"
  with_items:
    - AdminModules%
    - AdminParentModules%
  when: is_demo
  ignore_errors: yes

- name: prestashop - set demo right (edit)
  command: "php /var/www/{{ name }}/admin-tools/console.php profile:access -p demo2 -t {{ item }} -e"
  with_items:
    - AdminModules%
    - AdminParentModules%
  when: is_demo
  ignore_errors: yes

- name: prestashop - set demo right for default modules (none)
  command: "php /var/www/{{ name }}/admin-tools/console.php profile:access -p demo2 -t % -D -E -R"
  when: is_demo
  ignore_errors: yes

- name: prestashop - set demo right for module (display, edit)
  command: "php /var/www/{{ name }}/admin-tools/console.php profile:access -p demo2 -t {{ item }} -d -e"
  with_items : "{{ modules }}"
  when: is_demo
  ignore_errors: yes

- name: prestashop - change owner
  command: "chown -R www-data:www-data /var/www/{{ name }}"

- name: prestashop - set writing right on cache
  file:
    path: "/var/www/{{ name }}/app/cache/"
    state: directory
    recurse: yes
    mode: a+rwx

- name: prestashop - set writing right on cache
  file:
    path: "/var/www/{{ name }}/var/cache/"
    state: directory
    recurse: yes
    mode: a+rwx

