---
- name: prestashop - get sources
  git:
    repo: https://github.com/PrestaShop/PrestaShop.git
    dest: "/var/www/{{ item.name }}"
    version: "{{ item.version }}"
    accept_hostkey: yes
    force: yes
  with_items: "{{ apache_vhosts.prestashop }}"

- name: prestashop - get module sources
  git:
    repo: "git@github.com:madef/{{ item.1 }}.git"
    dest: "/var/www/{{ item.0.name }}/modules/{{ item.1 }}"
    accept_hostkey: yes
    force: yes
  with_subelements:
    - "{{ apache_vhosts.prestashop}}"
    - modules

- name: prestashop - get admin-tools
  git:
    repo: git@github.com:madef/ps-admin-tools.git
    dest: "/var/www/{{ item.name }}/admin-tools"
    accept_hostkey: yes
    force: yes
  with_items: "{{ apache_vhosts.prestashop }}"

- name: change owner
  command: "chown -R www-data:www-data /var/www/{{ item.name }}"
  with_items: "{{ apache_vhosts.prestashop }}"

- name: get settings.inc.php exists
  stat:
    path: "/var/www/{{ item.name }}/config/settings.inc.php"
  register: file
  with_items: "{{ apache_vhosts.prestashop }}"

- name: prestashop - install prestashop
  shell: |
    cd /var/www/{{ item.item.name }}
    php install-dev/index_cli.php --domain={{ item.item.domain }} --db_server={{ item.item.mysql.host }} --db_name=ps_{{ item.item.name }} --db_user={{ item.item.mysql.user }} --db_password={{ item.item.mysql.password }} --email=admin@madef.fr --password=test00test --firstname=admin --lastname=admin --newsletter=0
  with_items: "{{ file.results }}"
  when: item.item.is_demo or item.stat.exists == False

- name: prestashop - install modules
  command: "php /var/www/{{ item.0.name }}/admin-tools/console.php module:install -m {{ item.1 }}"
  with_subelements:
    - "{{ apache_vhosts.prestashop}}"
    - modules

- name: prestashop - upgrade modules
  command: "php /var/www/{{ item.0.name }}/admin-tools/console.php module:upgrade -m {{ item.1 }}"
  with_subelements:
    - "{{ apache_vhosts.prestashop}}"
    - modules

- name: prestashop - create demo profile
  command: "php /var/www/{{ item.name }}/admin-tools/console.php profile:create -n demo"
  with_items:
    - "{{ apache_vhosts.prestashop}}"
  when: item.is_demo

- name: prestashop - create demo user
  command: "php /var/www/{{ item.name }}/admin-tools/console.php employee:create -l demo -f demo -p demo00demo -e demo@demo.com -P demo -L en"
  with_items:
    - "{{ apache_vhosts.prestashop}}"
  when: item.is_demo

- name: prestashop - set demo right (display, add, remove, edit)
  command: "php /var/www/{{ item[0].name }}/admin-tools/console.php profile:access -p demo -t {{ item[1] }} -d -a -e -r"
  with_nested:
    - "{{ apache_vhosts.prestashop}}"
    - [ 'AdminCatalog', 'AdminProducts', 'AdminCategories', 'AdminFeatures', 'AdminManufacturers', 'AdminSuppliers', 'AdminTags', 'AdminAttachments', 'AdminModulesPositions']
  when: item.0.is_demo

- name: prestashop - set demo right (display)
  command: "php /var/www/{{ item[0].name }}/admin-tools/console.php profile:access -p demo -t {{ item[1] }} -d"
  with_nested:
    - "{{ apache_vhosts.prestashop}}"
    - [ 'AdminParentModules', 'AdminModules']
  when: item.0.is_demo

- name: prestashop - set demo right for module (display, edit)
  command: "php /var/www/{{ item[0].name }}/admin-tools/console.php profile:access -p demo -t {{ item[1] }} -d -e"
  with_subelements:
    - "{{ apache_vhosts.prestashop}}"
    - modules
  when: item.0.is_demo
