---
- hosts: http
  vars_files:
    - vars/passwords.yml
  pre_tasks:
    - name: install apache
      apt:
        name: apache2
        update_cache: yes
    - name: install php
      apt:
        name: [
          php7.3,
          php7.3-cli,
          php7.3-curl,
          php7.3-gd,
          php7.3-mysql,
          php7.3-xml,
          libapache2-mod-php7.3,
          php7.3-intl,
          php7.3-zip,
          php7.3-sqlite3, # for miniflux
          php7.3-mbstring, # for miniflux
          php7.3-mysql, # for poetrie
          composer,
          ruby-dev,
          rubygems-integration,
          zlibc,
          ruby-zip,
          zlib1g-dev
        ]
        #- name: Install gimli
      #gem:
        #name: gimli
          #state: present
    - name: Enable Apache mod
      apache2_module:
        state: present
        name: "{{ item }}"
      with_items:
        - rewrite
        - headers
        - ssl
        - session
        - socache_shmcb
  roles:
    - role: git
      when: application == 'adminprestashopxmlimporter'
    - role: apache-vhosts
      when: httpd == 'apache'
    - role: prestashop
      when: application == 'prestashop'
    - role: git
      when: application == 'git'
    - role: compta
      when: application == 'compta'
      #- role: letsencrypt
      #letsencrypt_webroot_path: "/var/www/{{ name }}"
      #letsencrypt_email: support@madef.fr
      #letsencrypt_cert_domains:
      #  - "{{ domain }}"
      #letsencrypt_renewal_command_args: '--renew-hook "systemctl restart apache2"'


