---
- hosts: http
  pre_tasks:
    - name: install apache
      apt:
        name: apache2
        update_cache: yes
    - name: install php
      apt:
        name: "{{ item }}"
      with_items:
        - php7.0
        - php7.0-cli
        - php7.0-curl
        - php7.0-gd
        - php7.0-mysql
        - php7.0-xml
        - libapache2-mod-php7.0
  roles:
    - apache-vhosts
    - prestashop
    #- role: letsencrypt
    #  letsencrypt_webroot_path: /var/www/responsivemenu
    #  letsencrypt_email: support@madef.fr
    #  letsencrypt_cert_domains:
    #    - responsivemenu.prestashop.demo.madef.fr
    #  letsencrypt_renewal_command_args: '--renew-hook "systemctl restart apache2"'


