---
- hosts: http
  vars_files:
    - vars/passwords.yml
  pre_tasks:
    - name: install apache
      apt:
        name: apache2
        update_cache: yes
    - name: install php
      apt:
        name: "{{ item }}"
      with_items:
        - php7.2
        - php7.2-cli
        - php7.2-curl
        - php7.2-gd
        - php7.2-mysql
        - php7.2-xml
        - libapache2-mod-php7.2
        - php7.2-intl
        - php7.2-zip
        - php7.2-sqlite3 # for miniflux
        - php7.2-mbstring # for miniflux
        - php7.2-mysql # for poetrie
        - composer
        - ruby-dev
        - rubygems-integration
        - zlibc
        - ruby-zip
        - zlib1g-dev
    - name: Install gimli
      gem:
        name: gimli
        state: present
  roles:
    - role: git
      when: application == 'adminprestashopxmlimporter'
    - role: apache-vhosts
      when: httpd == 'apache'
    - role: prestashop
      when: application == 'prestashop'
    - role: git
      when: application == 'git'
    - role: compta
      when: application == 'compta'
      #- role: letsencrypt
      #letsencrypt_webroot_path: "/var/www/{{ name }}"
      #letsencrypt_email: support@madef.fr
      #letsencrypt_cert_domains:
      #  - "{{ domain }}"
      #letsencrypt_renewal_command_args: '--renew-hook "systemctl restart apache2"'


