---
- hosts: sql
  vars_files:
    - vars/passwords.yml
  tasks:
      #- name: install mysql
      #apt:
      #  name: mariadb-server
      #  update_cache: yes
    - name: allow external connection
      lineinfile:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: '#bind-address = 127.0.0.1'
    - name: create users
      mysql_user:
        host: "{{ source_host_ip }}"
        name: "{{ mysql_user }}"
        password: "{{ passwords[name]['mysql'] }}"
        priv: "{{ mysql_database }}.*:ALL"
        state: present
    - name: create databases
      mysql_db:
        name: "{{ mysql_database }}"
        state: present
    - name: restart mysql
      service:
        name: mysql
        state: restarted
